# Generated by Django 6.1.1 on 2026-09-18 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Active', 'Active'), ('Archived', 'Archived')], default='Draft', max_length=20)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='commodities.commodity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(help_text='Driver or metric being adjusted', max_length=150)),
                ('original_value', models.CharField(max_length=100)),
                ('adjusted_value', models.CharField(max_length=100)),
                ('adjustment_pct', models.FloatField(help_text='Percentage change applied')),
                ('notes', models.TextField(blank=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='scenarios.scenario')),
            ],
        ),
        migrations.CreateModel(
            name='ScenarioResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_price_impact_pct', models.FloatField(help_text='Estimated price change percentage')),
                ('estimated_new_price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('confidence_interval_lower', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('confidence_interval_upper', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('methodology', models.CharField(default='Sensitivity Analysis (Preliminary)', max_length=100)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('warnings', models.TextField(blank=True, help_text='Caveats about score pending validation')),
                ('scenario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='scenarios.scenario')),
            ],
        ),
    ]
