# Generated by Django 6.1.1 on 2026-09-18 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scenarioinput',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='scenarioresult',
            options={'ordering': ['-computed_at']},
        ),
    ]
