# Generated by Django 6.1.1 on 2026-09-18 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('ENERGY', 'Energy'), ('PRECIOUS_METALS', 'Precious Metals'), ('INDUSTRIAL_METALS', 'Industrial Metals'), ('BATTERY_METALS', 'Battery Metals')], default='INDUSTRIAL_METALS', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('benchmark_unit', models.CharField(help_text='e.g. USD/mt, USD/troy oz', max_length=50)),
                ('current_price', models.DecimalField(decimal_places=4, default=0, max_digits=14)),
                ('price_change_pct_24h', models.FloatField(default=0.0)),
                ('price_change_pct_ytd', models.FloatField(default=0.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Commodities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CommodityDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('driver_type', models.CharField(choices=[('MACRO', 'Macroeconomic'), ('DEMAND', 'Physical Demand'), ('SUPPLY', 'Physical Supply'), ('POLICY', 'Policy & Geopolitical')], default='MACRO', max_length=20)),
                ('description', models.TextField()),
                ('impact_direction', models.CharField(choices=[('POSITIVE', 'Positive Impact'), ('NEGATIVE', 'Negative Impact'), ('MIXED', 'Mixed / Neutral')], default='POSITIVE', max_length=20)),
                ('correlation_score', models.FloatField(blank=True, help_text='Pending correlation screening', null=True)),
                ('confidence', models.CharField(default='Medium', max_length=20)),
                ('source', models.CharField(max_length=100)),
                ('latest_value', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='commodities.commodity')),
            ],
            options={
                'ordering': ['driver_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CommodityPriceSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=4, max_digits=14)),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('source', models.CharField(default='World Bank', max_length=50)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='commodities.commodity')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('commodity', 'date')},
            },
        ),
    ]
