# Generated by Django 6.1.1 on 2026-09-18 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataAuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(max_length=150)),
                ('available', models.CharField(choices=[('Yes', 'Available'), ('No', 'Not Available'), ('Partial', 'Partially Available')], default='Yes', max_length=20)),
                ('source', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=255)),
                ('earliest_date', models.DateField(blank=True, null=True)),
                ('latest_date', models.DateField(blank=True, null=True)),
                ('frequency', models.CharField(max_length=50)),
                ('unit', models.CharField(max_length=50)),
                ('missing_values', models.CharField(help_text='Count or rate e.g. 0% or <2%', max_length=100)),
                ('historical_depth', models.CharField(help_text='e.g. 10 years, 5 years', max_length=100)),
                ('proxy_required', models.BooleanField(default=False)),
                ('cost_rate_limit', models.CharField(help_text='Access limits and constraints', max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['metric'],
            },
        ),
        migrations.CreateModel(
            name='RawDataLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('Sectors', 'Sectors API'), ('World Bank', 'World Bank API'), ('FRED', 'FRED Federal Reserve API'), ('UN Comtrade', 'UN Comtrade API'), ('EIA', 'EIA Energy API')], max_length=50)),
                ('endpoint', models.CharField(max_length=255)),
                ('request_params', models.JSONField(blank=True, default=dict)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('status_code', models.IntegerField(default=200)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(db_index=True, max_length=150)),
                ('definition', models.TextField()),
                ('entity_type', models.CharField(choices=[('Commodity', 'Commodity'), ('Company', 'Company'), ('Macro', 'Macroeconomic')], default='Commodity', max_length=20)),
                ('entity_id', models.CharField(help_text='Code or Symbol e.g. COAL or ADRO.JK', max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('frequency', models.CharField(help_text='Daily, Monthly, Quarterly, Annual', max_length=30)),
                ('unit', models.CharField(max_length=50)),
                ('original_unit', models.CharField(blank=True, max_length=50)),
                ('transformation', models.CharField(default='None', help_text='e.g. None, YoY %, Log Diff, Normalized', max_length=50)),
                ('priority', models.CharField(choices=[('High', 'High Priority'), ('Medium', 'Medium Priority'), ('Low', 'Low Priority')], default='High', max_length=20)),
                ('confidence', models.CharField(choices=[('High', 'High Confidence'), ('Medium', 'Medium Confidence'), ('Low', 'Low Confidence')], default='High', max_length=20)),
                ('is_proxy', models.BooleanField(default=False)),
                ('proxy_description', models.TextField(blank=True)),
                ('observation_date', models.DateField(db_index=True)),
                ('value', models.DecimalField(decimal_places=4, max_digits=18)),
                ('raw_data_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metrics', to='evidence.rawdatalog')),
            ],
            options={
                'ordering': ['-observation_date', 'metric_name'],
            },
        ),
    ]
