# Generated by Django 6.1.1 on 2026-09-18 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commodities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('sector', models.CharField(default='Energy & Basic Materials', max_length=100)),
                ('sub_industry', models.CharField(default='Mining', max_length=100)),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('currency', models.CharField(default='IDR', max_length=10)),
                ('country', models.CharField(default='Indonesia', max_length=50)),
                ('exchange', models.CharField(default='IDX', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['ticker'],
            },
        ),
        migrations.CreateModel(
            name='CompanyResilience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_to_equity', models.FloatField(default=0.0)),
                ('current_ratio', models.FloatField(default=0.0)),
                ('ebitda_margin', models.FloatField(default=0.0)),
                ('free_cash_flow', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('net_cash_position', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('reserve_life_years', models.FloatField(blank=True, null=True)),
                ('resilience_score', models.FloatField(default=0.0, help_text='Preliminary resilience index (0-100)')),
                ('scoring_status', models.CharField(default='Pending Validation', help_text='Scoring methodology status - not final until backtested', max_length=50)),
                ('as_of_date', models.DateField()),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resilience_profile', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyCommodityExposure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revenue_share_pct', models.FloatField(help_text='Percentage of total revenue derived from this commodity (0-100)')),
                ('production_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('production_unit', models.CharField(blank=True, max_length=50)),
                ('cash_cost_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('exposure_score', models.FloatField(default=0.0, help_text='Normalized exposure metric score (0-100)')),
                ('notes', models.TextField(blank=True)),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_exposures', to='commodities.commodity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commodity_exposures', to='companies.company')),
            ],
            options={
                'ordering': ['-revenue_share_pct'],
                'unique_together': {('company', 'commodity')},
            },
        ),
    ]
