# Generated by Django 6.1.1 on 2026-09-18 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companycommodityexposure',
            name='exposure_score',
            field=models.FloatField(blank=True, default=None, help_text='Preliminary exposure score (0-100); null when unavailable', null=True),
        ),
        migrations.AlterField(
            model_name='companycommodityexposure',
            name='revenue_share_pct',
            field=models.FloatField(blank=True, help_text='Percentage of total revenue derived from this commodity (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='companyresilience',
            name='resilience_score',
            field=models.FloatField(blank=True, default=None, help_text='Preliminary resilience index (0-100); null when unavailable', null=True),
        ),
    ]
